# Generated by Django 5.1.5 on 2025-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
