# Generated by Django 5.1.7 on 2025-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_coursemodule_lesson_coursematerial_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
