# Generated by Django 5.2.7 on 2025-11-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0009_lesson_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='modules', to='courses_app.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses_app.coursematerial'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_set', to='courses_app.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_set', to='courses_app.coursemodule'),
        ),
    ]
