# Generated by Django 5.2.7 on 2025-11-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0010_coursemodule_is_published_coursemodule_lessons_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
    ]
