# Generated by Django 5.2.7 on 2025-11-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0011_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='lessons',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses_app.coursemodule'),
        ),
    ]
