# Generated by Django 5.2.7 on 2025-11-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0012_remove_coursemodule_lessons_alter_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file for secure streaming.', null=True, upload_to='lesson_videos/'),
        ),
    ]
