# Generated by Django 5.2.7 on 2025-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0013_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
