# Generated by Django 5.2.7 on 2025-12-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0014_course_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_token', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(max_length=255)),
                ('course_duration', models.PositiveIntegerField(default=0)),
                ('instructor_name', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('course_description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_text', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses_app.enrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='courses_app_certifi_4b4f2d_idx'), models.Index(fields=['verification_token'], name='courses_app_verific_a3ce79_idx')],
            },
        ),
    ]
