# Generated by Django 5.2.7 on 2026-05-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0015_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in minutes'),
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Video title/caption', max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload video file for secure streaming', null=True, upload_to='lesson_videos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of videos')),
                ('position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('inline', 'Inline')], default='top', help_text='Where to place this video relative to content', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('is_preview', models.BooleanField(default=False, help_text='Allow preview for non-enrolled users')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses_app.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or HTML', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses_app.lesson')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='courses_app.lessonvideo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
